project_id = "vnyvffrvacghnenijtqg"

[functions.export-database]
verify_jwt = true

[functions.stripe-webhook]
verify_jwt = false

[functions.whmcs-webhook]
verify_jwt = false

[functions.track-referral-click]
verify_jwt = false

[functions.trial-create]
verify_jwt = false

[functions.validate-trial-signup]
verify_jwt = false

[functions.record-trial-usage]
verify_jwt = false

[functions.delete-user]
verify_jwt = true

[functions.purchase-subscriptions]
verify_jwt = true

[functions.nowpayments-webhook]
verify_jwt = false
